accounts/urls.py
app_name='accounts'

from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.urls import path

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accounts/login.html'),
    name='login'),

    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/(?P<pk>\d+)/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),

    path('password-reset/',
    PasswordResetView.as_view(template_name='accounts/password_reset.html',
    success_url=reverse_lazy('accounts:password_reset_done')),
    {'email_template_name': 'accounts/password_reset_email.html'},
    name='password_reset'),

    path('password-reset/done/',
    PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
    name='password_reset_done'),

    path('password-reset/confirm/<uidb64>/<token>/',
    PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')),
    name='password_reset_confirm'),

    path('password-reset/complete/',
    PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    name='password_reset_complete'),

]

home/urls.py
from django.urls import path, re_path
from home.views import HomeView
from . import views

app_name='home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
    views.change_friends, name='change_friends'),
    path('counter/', views.counter, name='counter'),
]

maxx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from maxx import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))
    class Meta:
        model = Post
        fields = ('post',)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from home.forms import HomeForm
from home.models import Post, Friend

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        friends = Friend.objects.filter(current_user=request.user)

        args = {
            'form': form, 'posts': posts, 'users': users, 'friends': friends,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
        return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, {'form': form})

def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('home:home')

def counter(request, pk):
    Counter.objects.filter(pk=pk).update(views=F('views')+1)
    return render(request, "home/counter.html")

home/templates/home/counter.html
{% extends 'base.html' %}
{% load static %}

  {% block head %}
    <title> Social Counter </title>
  {% endblock %}

  {% block body %}
  <div class="container">
      <h1>Have you been on social media today?</h1><br>
          <form class="form" method="post" name="counter">
            {% csrf_token %}
            {{ form.as_p }}
          </form>
      <button type="submit" value="Login">Yes</button>
      <button type="submit" value="Login">No</button>
  </div>
  {% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

  {% block head %}
    <title> Homepage </title>
  {% endblock %}

  {% block body %}
  <div class="container1">
    <div class="col-md-6">
      <h1>Write a status!</h1>
      <form class="form" method="post" input type ='text'>
        {% csrf_token %}
        {{ form.post }}
        <br>
        <button type="submit" value="Login">Post it</button>
      </form>
      <h2>{{ text }}</h2>
      {% for post in posts %}
        <h1>{{ post.post }}</h1>
        <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
      {% endfor %}
  </div>
  <div class="col-md-6">
    <h3>Your Friends</h3>  </div>
    {% for friend in friends %}
      <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
        <h3>{{ friend.username }}</h3>
      </a>
      <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
        <button type="button" class="btn btn-default" type="submit">Remove Friend</button>
      </a>
    {% endfor %}
    <h3>Other people on Kanso</h3>
    {% for user in users %}
      <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
        <h3>{{ user.username }}</h3>
      </a>
      {% if not user in friends %}
      <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
        <button type="button" class="btn btn-success" type="submit">Add Friend</button>
      </a>
      {% endif %}
    {% endfor %}
  </div>
  {% endblock %}