accounts/urls.py
app_name='accounts'

from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.urls import path

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accounts/login.html'),
    name='login'),

    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/(?P<pk>\d+)/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),

    path('password-reset/',
    PasswordResetView.as_view(template_name='accounts/password_reset.html',
    success_url=reverse_lazy('accounts:password_reset_done')),
    {'email_template_name': 'accounts/password_reset_email.html'},
    name='password_reset'),

    path('password-reset/done/',
    PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
    name='password_reset_done'),

    path('password-reset/confirm/<uidb64>/<token>/',
    PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')),
    name='password_reset_confirm'),

    path('password-reset/complete/',
    PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    name='password_reset_complete'),

]

home/urls.py
from django.urls import path, re_path
from home.views import HomeView
from . import views

app_name='home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
    views.change_friends, name='change_friends'),
    path('counter/', views.counter, name='counter'),
]

maxx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from maxx import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Roanoke')

class UserProfile(models.Model):
    user= models.OneToOneField(User, on_delete=models.DO_NOTHING)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    objects = models.Manager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'password'
        ]

accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:home')

    else:
        form = RegistrationForm()
    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')

    else:
        form = EditProfileForm(instance=request.user)
    args={'form':form}
    return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:view_profile')
        else:
            return redirect('accounts:change_password')

    else:
        form = PasswordChangeForm(user=request.user)

    args={'form':form}
    return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial scale=1.0">

        {% load static %}
        <link rel="stylesheet" href="{% static '/accounts/style.css' %}" type="text/css">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
      <div class="wrapper"><!--/.header -->
        <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar" aria-expanded="false"
            aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/home">Kanso</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar">
              <li><a href="{% url 'home:home' %}">Home</a></li>
              <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
              <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
              <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:register' %}">Register</a></li>
              <li><a href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      {% block body %}
        <h1>Base</h1>
      {% endblock %}
    </body>
  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script
  src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
  crossorigin="anonymous"></script>
</html>